package com.example.paola.weatherapp.data.db

import java.util.*

/**
 * Created by paolafalcomata on 20/09/2017.
 * Map => delegate use a MutableMap inthe constructor of the object
 * val dayForecast = DayForecast(mapOf(
 *                          "date" to 12345647855
 *                          "description" to "myDescription"
 *                          "high" to 12
 *                          ...
 *                   ))
 */
class DayForecast(val map: MutableMap<String, Any?>) {
    var _id: Long by map
    var date: Long by map
    var description: String by map
    var high: Int by map
    var low: Int by map
    var iconUrl: String by map
    var cityId: Long by map


    // No assigning an id because it will be auto-generated by SQLite
    constructor(date: Long, description: String, high: Int, low: Int, iconUrl: String, cityId: Long) : this(HashMap()) {
        this.date = date
        this.description = description
        this.high = high
        this.low = low
        this.iconUrl = iconUrl
        this.cityId = cityId
    }


}

class CityForecast(val map: MutableMap<String, Any?>, val dailyForecast: List<DayForecast>) {
    var _id: Long by map
    var city: String by map
    var country: String by map

    constructor(_id: Long, city: String, country: String, dailyForecast: List<DayForecast>) : this(HashMap(), dailyForecast) {
        this._id = _id
        this.city = city
        this.country = country
    }



}
