package com.example.paola.weatherapp.data.server

import com.example.paola.weatherapp.data.db.ForecastDb
import com.example.paola.weatherapp.domain.dataSources.ForecastDataSource
import com.example.paola.weatherapp.domain.models.ForecastList

/**
 * Created by paolafalcomata on 20/09/2017.
 */
class ForecastServer(private val dataMapper: ServerDataMapper = ServerDataMapper(),
                     private val forecastDb: ForecastDb = ForecastDb()) : ForecastDataSource {


    override fun requestDayForecast(id: Long) = throw UnsupportedOperationException()

    override fun requestForecastByZipCode(zipCode: Long, date: Long): ForecastList? {
        // Request to server the forecast
        val forecastResult = ForecastRequest(zipCode.toString()).execute()
        // Convert the response to model
        val list = dataMapper.convertForecastResultToDomain(zipCode, forecastResult)
        // Save the list to the DB
        forecastDb.saveForecast(list)
        // Get forecast from DB because we need the row ids that were self-generated by the insert query
        return forecastDb.requestForecastByZipCode(zipCode, date)
    }


}